export class Historico {

  //entrevista
  public idPaciente: string;
  public idsaeapp_historico: string;
  public internacoes: number;
  public motivoInternacao: string;
  public cardiopatia: boolean;
  public convulsao: boolean;
  public asma: boolean;
  public drogas: boolean;
  public motivo: Array<string>;
  public outrosAntecedentes:string;
  public has: boolean;
  public tabagismo: boolean;
  public diabetesMellitus: boolean;
  public alcoolismo: boolean;
  public antecedentesArray: Array<string>;
  public antecedentes: string;
  public qtdeAntecedentes: number;
  public alergias: string;
  public vacinas: string;
  //avaliacao neurologica
  public consciencia: string;
  public glasgow: string;
  public pupilas: string;
  public mmss_direito: string;
  public mmss_esquerdo: string;
  public mmii_direito: string;
  public mmii_esquerdo: string;
  public falaELinguagem: string;
  //Oxigenacao
  public O2: string;
  public SpO: string;
  public FR: string;
  public oxigenacao: string;
  public traqueostomiaMascara: string;
  public ventilacaoMecanica: boolean;
  public ventilacaoMecanicaTipo: string;
  public FiO2: string;
  public Peep: string;
  public SpO2: string;
  public ventilacaoMecanicaOxigenacao: string;
  public auscultaPulmonar_MvPresente: string;
  public auscultaPulmonar_Ruidos: string;
  public presencaoDeTosse_xpectoracao: string;
  public aspiracaoQuantidade: string;
  public aspiracaoCaracteristica: string;
  public drenagemQuantidade: string;
  public drenagemCaracteristica: string;
  public drenagemToracicaDTE: boolean;
  public drenagemToracicaDTD: boolean;
  public mamas: string;
  //avaliacao Cardiovascular
  public avaliacaoCardiovascular_Fc: string;
  public avaliacaoCardiovascular_Pa: string;
  public avaliacaoCardiovascular_PVC: string;
  public avaliacaoCardiovascular_PAM: string;
  public pulso: string;
  public pulsoImpalpavel: string;
  public pulsoPalpabilidade: string;
  public presencaDeEdema: string;
  public presencaDeEdemaPes: boolean;
  public presencaDeEdemaMMII: boolean;
  public presencaDeEdemaMMSS: boolean;
  public presencaDeEdemaAnasarca: boolean;
  //hidratacao e eliminacao vesical
  public turgidezDaPele: string;
  public eliminacaoUrinariaEspontanea: boolean;
  public eliminacaoUrinariaRetencao: boolean;
  public hidratacao_Caracteristicas: string;
  public eliminacaoUrinaria: string;
  public eliminacaoUrinaria_Volume: string;  
  public eliminacaoUrinariaIncontinencia: boolean;
  public eliminacaoUrinariaSVD: boolean;
  public eliminacaoUrinariaDispositivoUrinario: boolean;
  public caracteristicasDisuria: boolean;
  public caracteristicasOliguria: boolean;
  public caracteristicasAnuria: boolean;
  public caracteristicasPoliuria: boolean;
  public caracteristicasHematuria: boolean;
  public caracteristicasOutros: string;
  //alimentacao e eliminacao
  public tipoDeDieta: string;
  public glicemia: string;
  public alimentacao_ViasDeAdministracao: string;
  public viasDeAdministracaoOral: boolean;
  public viasDeAdministracaoSNG: boolean;
  public viasDeAdministracaoSNE: boolean;
  public viasDeAdministracaoParenteral: boolean;
  public viasDeAdministracaoOutros: string;
  public abdome: string;
  public abdomePlano: boolean;
  public abdomeGloboso: boolean;
  public abdomeDistendido: boolean;
  public abdomeDolorosoAPalpacao: boolean;
  public abdomeOutros: string;
  public RHA: string;
  public ausentes: boolean;
  public diminuido: boolean;
  public aumentado: boolean;
  public ostomiaLocal: string;
  public ostomiaCaracteristica: string;
  public eliminacaoIntestinal: string;
  public eliminacaoIntestinal_frequencia: string;
  public eliminacaoIntestinal_outros: string;
  //aspectos cutaneo muscosa
  public lesoes: string;
  public Cianose: boolean;
  public Ictericia: boolean;
  public Petequias: boolean;
  public Corado: boolean;
  public Hipocorado: boolean;
  public Hipercorado: boolean;
  public Equimoses: boolean;
  public Hematomas: boolean;
  public Escoriacoes: boolean;
  public aspectosCutaneoMucosaOutros: string;
  public modalidade: string;
  public AVP_tempo: string;
  public AVP_local: string;
  public pele_temperatura: string;
  public ictericia: boolean;
  public edemaDeConjuntiva: boolean;
  public olhosOutros: string;
  public olhos: string;
  public pele: string;
  public CVC_tempo: string;
  public CVC_local: string;
  public dreno_local;
  public dreno_tipo: string;
  public genitalia:string;
  public genitaliaSemAnormalidades: boolean;
  public genitaliaSecrecao: boolean;
  public genitaliaOutros: string;
  //seguranca Fisica
  public necessidadeDeContencao;
  public riscoParaQueda;
  public escore: string;
  public observacoes: string;

  constructor() {

    //entrevista
    this.idsaeapp_historico = "0";
    this.idPaciente = "0";
    this.internacoes = 0;
    this.motivoInternacao = ""
    this.cardiopatia = false;
    this.convulsao = false;
    this.asma = false;
    this.drogas = false;
    this.motivo = [];
    this.has = false;
    this.tabagismo = false;
    this.diabetesMellitus = false;
    this.alcoolismo = false;
    this.antecedentesArray = [];
    this.antecedentes = "";
    this.qtdeAntecedentes = 0;
    this.alergias = "";
    this.vacinas = "";
    this.outrosAntecedentes = "";
    //avaliacao neurologica
    this.consciencia = "";
    this.glasgow = "0";
    this.pupilas = "";
    this.mmii_esquerdo = "";
    this.mmii_direito = "";
    this.mmss_esquerdo = "";
    this.mmss_direito = "";
    this.falaELinguagem = "";
    //Oxigenacao
    this.O2 = "";
    this.SpO = "";
    this.modalidade = "";
    this.FR = "";
    this.oxigenacao = "";
    this.traqueostomiaMascara = "";
    this.ventilacaoMecanica = false;
    this.ventilacaoMecanicaTipo = "";
    this.ventilacaoMecanicaOxigenacao = "";    
    this.FiO2 = "";
    this.Peep = "";
    this.SpO2 = "";
    this.auscultaPulmonar_MvPresente = "";
    this.auscultaPulmonar_Ruidos = "";
    this.presencaoDeTosse_xpectoracao = "";
    this.aspiracaoQuantidade = "";
    this.aspiracaoCaracteristica = "";
    this.drenagemQuantidade = "";
    this.drenagemCaracteristica = "";
    this.drenagemToracicaDTE = false;
    this.drenagemToracicaDTD = false;
    this.mamas = "";
    //avaliacao Cardiovascular
    this.avaliacaoCardiovascular_Fc = "";
    this.avaliacaoCardiovascular_Pa = "";
    this.avaliacaoCardiovascular_PVC = "";
    this.avaliacaoCardiovascular_PAM = "";
    this.pulso = "";
    this.pulsoImpalpavel = "";
    this.pulsoPalpabilidade = "";
    this.presencaDeEdema = "";
    this.presencaDeEdemaPes = false;
    this.presencaDeEdemaMMII = false;
    this.presencaDeEdemaMMSS = false;
    this.presencaDeEdemaAnasarca = false;
    //hidratacao e eliminacao vesical
    this.turgidezDaPele = "";
    this.eliminacaoUrinaria = "";
    this.eliminacaoUrinaria_Volume = "";
    this.hidratacao_Caracteristicas = "";
    this.eliminacaoUrinariaEspontanea = false;
    this.eliminacaoUrinariaRetencao = false;
    this.eliminacaoUrinariaIncontinencia = false;
    this.eliminacaoUrinariaSVD = false;
    this.eliminacaoUrinariaDispositivoUrinario = false;
    this.caracteristicasDisuria = false;
    this.caracteristicasOliguria = false;
    this.caracteristicasAnuria = false;
    this.caracteristicasPoliuria = false;
    this.caracteristicasHematuria = false;
    this.caracteristicasOutros = "";
    //alimentacao e eliminacao
    this.tipoDeDieta = "";
    this.glicemia = "";
    this.alimentacao_ViasDeAdministracao = "";
    this.viasDeAdministracaoOral = false;
    this.viasDeAdministracaoSNG = false;
    this.viasDeAdministracaoSNE = false;
    this.viasDeAdministracaoParenteral = false;
    this.viasDeAdministracaoOutros = "";
    this.abdome = "";
    this.abdomePlano = false;
    this.abdomeGloboso = false;
    this.abdomeDistendido = false;
    this.abdomeDolorosoAPalpacao = false;
    this.abdomeOutros = "";
    this.RHA = "";
    this.ausentes = false;
    this.diminuido = false;
    this.aumentado = false;
    this.ostomiaLocal = "";
    this.ostomiaCaracteristica = "";
    this.eliminacaoIntestinal = "";
    this.eliminacaoIntestinal_frequencia = "";
    this.eliminacaoIntestinal_outros = "";
    //aspectos cutaneo muscosa
    this.lesoes = "";
    this.pele = "";
    this.Cianose = false;
    this.Ictericia = false;
    this.Petequias = false;
    this.Corado = false;
    this.Hipocorado = false;
    this.Hipercorado = false;
    this.Equimoses = false;
    this.Hematomas = false;
    this.Escoriacoes = false;
    this.aspectosCutaneoMucosaOutros = "";
    this.pele_temperatura = "";
    this.ictericia = false;
    this.edemaDeConjuntiva = false;
    this.olhosOutros = "";
    this.olhos = "";
    this.AVP_local = "";
    this.AVP_tempo = "";
    this.CVC_local="";
    this.CVC_tempo= "";
    this.dreno_local = "";
    this.dreno_tipo = "";
    this.genitalia = "";
    this.genitaliaSemAnormalidades = false;
    this.genitaliaSecrecao = false;
    this.genitaliaOutros = "";
    //seguranca Fisica
    this.necessidadeDeContencao="";
    this.riscoParaQueda="";
    this.escore = "";
    this.observacoes = "";
  }
}
